<?php

namespace BackEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IngresosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngresosRepository extends EntityRepository
{
}
