<?php

namespace BackEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RolUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolUsuarioRepository extends EntityRepository
{
}
