<?php

namespace BackEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoGastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoGastoRepository extends EntityRepository
{
}
