services:
  gestor.front.principalService:
    class: FrontEndBundle\Services\principalService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.empleadoService:
    class: FrontEndBundle\Services\empleadoService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.loginService:
    class: FrontEndBundle\Services\loginService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.logoutService:
    class: FrontEndBundle\Services\logoutService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.registrarService:
    class: FrontEndBundle\Services\registrarService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.comprobarUsuarioService:
    class: FrontEndBundle\Services\comprobarUsuarioService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.clientesService:
    class: FrontEndBundle\Services\clientesService
    arguments: ["@doctrine.orm.entity_manager"]
  
  gestor.front.horarioService:
    class: FrontEndBundle\Services\horarioService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.luzService:
    class: FrontEndBundle\Services\luzService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.aguaService:
    class: FrontEndBundle\Services\aguaService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.proveedoresService:
    class: FrontEndBundle\Services\proveedoresService
    arguments: ["@doctrine.orm.entity_manager"]
  
  gestor.front.perfilService:
    class: FrontEndBundle\Services\perfilService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.activoEmpleadoService:
    class: FrontEndBundle\Services\activoEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.bajaEmpleadoService:
    class: FrontEndBundle\Services\bajaEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.bajasClientesService:
    class: FrontEndBundle\Services\bajasClientesService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.estadisticasPrincipalService:
    class: FrontEndBundle\Services\estadisticasPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.gastoAguaService:
    class: FrontEndBundle\Services\gastoAguaService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.gastoLuzService:
    class: FrontEndBundle\Services\gastoLuzService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.gastoProveedoresService:
    class: FrontEndBundle\Services\gastoProveedoresService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.gastosInesperadosPrincipalService:
    class: FrontEndBundle\Services\gastosInesperadosPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.graficaPrincipalService:
    class: FrontEndBundle\Services\graficaPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.nuevosClientesService:
    class: FrontEndBundle\Services\nuevosClientesService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.tablasPrincipalService:
    class: FrontEndBundle\Services\tablasPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.vacacionesEmpleadoService:
    class: FrontEndBundle\Services\vacacionesEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.widgetsVistaService:
    class: FrontEndBundle\Services\widgetsVistaService
    arguments: ["@session", "@doctrine.orm.entity_manager", "@gestor.front.widgetsVistaService"]




















