services:
  gestor.front.vistaService:
    class: FrontEndBundle\Services\vistaService
    arguments: ["@session","@doctrine.orm.entity_manager", "@gestor.front.widgetsVistaService"]

  gestor.front.loginService:
    class: FrontEndBundle\Services\loginService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.logoutService:
    class: FrontEndBundle\Services\logoutService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.registrarService:
    class: FrontEndBundle\Services\registrarService
    arguments: ["@doctrine.orm.entity_manager"]

  gestor.front.comprobarUsuarioService:
    class: FrontEndBundle\Services\comprobarUsuarioService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.activoEmpleadoService:
    class: FrontEndBundle\Services\activoEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.bajaEmpleadoService:
    class: FrontEndBundle\Services\bajaEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.bajasClientesService:
    class: FrontEndBundle\Services\bajasClientesService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.estadisticasPrincipalService:
    class: FrontEndBundle\Services\estadisticasPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.aguaGastoAguaService:
    class: FrontEndBundle\Services\aguaGastoAguaService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.luzGastoLuzService:
    class: FrontEndBundle\Services\luzGastoLuzService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.proveedoresGastoProveedoresService:
    class: FrontEndBundle\Services\proveedoresGastoProveedoresService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.gastosInesperadosPrincipalService:
    class: FrontEndBundle\Services\gastosInesperadosPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.graficaPrincipalService:
    class: FrontEndBundle\Services\graficaPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.nuevosClientesService:
    class: FrontEndBundle\Services\nuevosClientesService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.tablasPrincipalService:
    class: FrontEndBundle\Services\tablasPrincipalService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.vacacionesEmpleadoService:
    class: FrontEndBundle\Services\vacacionesEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.widgetsVistaService:
    class: FrontEndBundle\Services\widgetsVistaService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.aguaTablaAguaService:
    class: FrontEndBundle\Services\aguaTablaAguaService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.luzTablaLuzService:
    class: FrontEndBundle\Services\luzTablaLuzService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.proveedoresTablaProveedoresService:
    class: FrontEndBundle\Services\proveedoresTablaProveedoresService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.empleadoTablaEmpleadoService:
    class: FrontEndBundle\Services\empleadoTablaEmpleadoService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.clienteTablaClientesService:
    class: FrontEndBundle\Services\clienteTablaClientesService
    arguments: ["@session", "@doctrine.orm.entity_manager"]


  gestor.front.horarioTablaHorarioService:
    class: FrontEndBundle\Services\horarioTablaHorarioService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

  gestor.front.tablaPerfilService:
    class: FrontEndBundle\Services\tablaPerfilService
    arguments: ["@session", "@doctrine.orm.entity_manager"]

















