<?php

namespace GestorBackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GastosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastosRepository extends EntityRepository
{
}
